Nextdoor/kingpin

kingpin/actors/aws/elb.py, kingpin/actors/aws/sqs.py, kingpin/actors/base.py, kingpin/actors/group.py, kingpin/actors/hipchat.py, kingpin/actors/librato.py, kingpin/actors/misc.py, kingpin/actors/rightscale/server_array.py, kingpin/actors/rollbar.py, kingpin/actors/test/test_base.py, kingpin/constants.py
Sometimes None is a valid default value, and it should not be reserved
to identify a required parameter. This change converts all actors to use
a REQUIRED identifier (meta class).
=> Use REQUIRED constant instead of None for options

README.md, docs/actors/group.Async.md, docs/actors/group.Sync.md, kingpin/actors/base.py, kingpin/actors/group.py, kingpin/actors/misc.py, kingpin/actors/test/test_base.py, kingpin/actors/test/test_group.py, kingpin/actors/test/test_misc.py, kingpin/bin/deploy.py, kingpin/test/test_utils.py, kingpin/utils.py
Issue #143 
This request adds the concept of an `init_context` to our `BaseActor` which can be used to dynamically fill in the actor `options` at init time. This is used to allow a single actor definition in a `group.Sync` or `group.Async` to be re-used multiple times to create new actors. For example:
```json5
{ "desc": "Send out hipchat notifications",
"actor": "group.Sync",
"warn_on_failure": true,
"options": {
"contexts": [ { "ROOM": "Systems" } ],
"acts": [
{ "desc": "Send ending notifications to {ROOM}...", "actor": "group.Async",
"options": {
"contexts": [ { "APP": "App1" }, { "APP": "App2" } ],
"acts": [
{ "desc": "Notify End {ROOM}", "actor": "hipchat.Message", "options": { "room": "{ROOM}", "message": "Hey room .. I'm done with {APP}" } }
]
}
}
]
}
}
```
This creates the …
=> Add actor 'initialization context' support.

kingpin/actors/rollbar.py, kingpin/actors/test/test_rollbar.py
Rollbar has changed their response code on invalid_credentials
to respond with a 401 instead of a 403. Support both, just in case
they return to the old model.
=> Handle 401 and 403 response codes the same.

kingpin/actors/rightscale/test/integration_server_array.py
1. Ensure that we never launch more than 1 instance, even if
that instance takes forever. Effectively disables RS AutoScaling.
2. Fix an integration test that was supposed to break and throw/catch
an exception, but wasn't because it was a bad copy-paste.
=> actors.rightscale.server_array integration test fixes.

docs/actors/rightscale.server_array.Clone.md, examples/rightscale_rolling_array_relaunch.json, kingpin/actors/rightscale/server_array.py, kingpin/actors/rightscale/test/test_server_array.py
(Solves issue #222 without writing a whole new actor)
The only reason that a "relaunch" of an existing ServerArray couldn't be
automated with existing actors was that the
rightscale.server_array.Clone actor was extremely strict about whether
the source/destination arrays already existed or not. By allowing this
to be configurable, you can write a script that acts on not-yet-existing
arrays.
Included in this change is an example of a "relaunch" Kingpin script.
=> Allow setting of the 'strictness' of the rightscale.server_array.Clone actor

kingpin/actors/rightscale/server_array.py, kingpin/actors/rightscale/test/test_server_array.py
This allows '10' to be passed in (or more likely, using contexts,
something like '{COUNT}') and then auto converts it to an int.
=> Accept 'string counts' for rightscale.server_array.Launch.

requirements.txt
Something in the way our code is calling multiple tasks and yielding on
them is causing Tornado 4.1 to log out all the exceptions again,
regardless of whether we're doing it or not. Until this is resolved,
pinning our Tornado to < 4.1.
I have opened an issue with the Tornado team asking for guidance:
https://github.com/tornadoweb/tornado/issues/1378
This handles #232 -- where really we're handling the code fine, but there is extra logging being generated by Tornado that we were not expecting.
=> Force Tornado < 4.1 due to a behavioral change in Exception logging.

kingpin/actors/aws/base.py, kingpin/actors/aws/cloudformation.py, kingpin/actors/aws/elb.py, kingpin/actors/aws/iam.py, kingpin/actors/aws/sqs.py, kingpin/actors/rightscale/api.py, requirements.txt
Tornado 4.1 was much louder about exceptions that it did not believe had been handled in asynchronous Future objects. This patch cleans up our use of these Futures while also creating much more clear output to the user about which instances failed to execute a script.
This also handles issue #229, as well as #236.
=> Support Tornado 4.1+ by ensuring all exceptions are caught and handled.

CHANGELOG.md, kingpin/actors/rightscale/api.py
This is just a safety check. If it fails, we should at least try a few
times.
=> Add the @sync_retry decorator to the make_generic_request() call.

kingpin/actors/aws/base.py, kingpin/actors/support/api.py
Close #250 (again)
* Delay in retry decorator bumped because original delay was
insignificant enough to still end up failing
=> Add `Rate exceeded` to retriable exceptions.

kingpin/actors/misc.py
Just like the Group actors, the Macro actor does nothing but call other
actors. Its timeout should be 0 by default.
=> Set the default timeout for the misc.Macro actor to 0 (unlimited).

docs/actors/rightscale.server_array.Update.md, kingpin/actors/rightscale/base.py, kingpin/actors/rightscale/server_array.py, kingpin/actors/rightscale/test/integration_server_array.py, kingpin/actors/rightscale/test/test_base.py, kingpin/actors/rightscale/test/test_server_array.py
Per
http://reference.rightscale.com/api1.5/resources/ResourceServerArrays.html#create_parameters,
and
http://support.rightscale.com/12-Guides/RightScale_API_1.5/1_Overview/Parameters/index.html:
RightScale has a concept of input 'arrays' that are passed in as funny
looking key=value pairs. For example, passing in a schedule for
AutoScaling an array in RightScale looks like this:
server_array[elasticity_params][schedule][][min_count]=1
server_array[elasticity_params][schedule][][day]=Sunday
server_array[elasticity_params][schedule][][max_count]=2
server_array[elasticity_params][schedule][][time]=0700
server_array[elasticity_params][schedule][][max_count]=2
server_array[elasticity_params][schedule][][day]=Monday
server_array[elasticity_params][schedule][][min_count]=1 …
=> Handle RightScales concept of 'array values'.

kingpin/actors/rightscale/base.py, kingpin/actors/rightscale/test/test_base.py
The python-rightscale library is supposed to
(https://github.com/brantai/python-rightscale/commit/2a8c0f572c4b13de03cbf67a1253c135b45ff2ca)
honor the RightScale OAUTH2 token expiration date and generate a new
token when it expires. This code worked when I wrote it and individually
tested it inside the confines of that library itself.
However, we are still seeing cases where extremely long running
processes in Kingpin will hit a 403 error from RightSCale roughly 2
hours after the initial OAUTH token was created. Given the complexity of
firing off all of our API calls into little mini threads everywhere, I'm
concerned that there is some kind of non-thread-safe code issue here.
To simplify things, I'm removing the cross-actor RightScale API object
sharing. Each actor will instantiate its own …
=> Disable the cross-actor RightScale API Object sharing.

kingpin/actors/rightscale/api.py, kingpin/actors/rightscale/server_array.py, kingpin/actors/rightscale/test/integration_server_array.py, kingpin/actors/rightscale/test/test_api.py, kingpin/actors/rightscale/test/test_server_array.py
Sometimes you want to update the 'Next Instance' settings of a
RightScale Array -- these include things like the Server Template, IP
Association settings, AMI Image HREFs and more.
This actor searches for your ServerArray, grabs its 'Next Instance'
object, and then updates that object with the parameters you've passed
in.
Additionally, a custom helper has been added so that if you use
'default' as your 'image_href', we automatically discover the default
AMI image for your MCI and associate that image_href for you.
CC: @siminm
=> New Actor: rightscale.server_array.UpdateNextInstance

kingpin/actors/packagecloud.py
Without this, Tornado defaults to a `20s` timeout and then throws a 599 error on its own. The PackageCloud API sometimes takes a while to respond if you're asking for a ton of data.
=> Use a 120s timeout when interacting with PackageCloud

kingpin/actors/aws/elb.py, kingpin/actors/aws/test/test_elb.py, kingpin/actors/test/integration_hipchat.py
By default, the safe thing to do is to determine the "connection
draining" time configured in the ELB and wait until that time has passed
before we return from the actor. Without this, a host might move on to
another state while still handling web requests.
=> Issue 306: Wait for all ELB connections to drain.

kingpin/test/test_utils.py, kingpin/utils.py
When you call Kingpin thorugh the `main.py` access method (using the zip
file, for example), your PYTHONPATH is not properly set so Kingpin
cannot necessarily find the actors unless they are fully qualified (eg
`actors.misc.Sleep`).
Now we attempt to start off by finding the module name with
`kingpin.actors` and then `actors` prefixed to it. We fall back to
finding the actor name without any prefix -- in case a user has
developed their own actor.
=> Search for Actor names with the Kingpin prefixes first.

kingpin/bin/deploy.py
This is the correct method to use -- it handles the various error cases,
logs appropriately and exits with the right error code.
Closes #314
@Nrvale, here's an example of it working now:
```
(.venv)Matts-MacBook:kingpin diranged$ python kingpin/bin/deploy.py --actor lasdfjk
2015-12-21 09:53:43,416 INFO      Rehearsing... Break a leg!
2015-12-21 09:53:43,416 WARNING   Could not import kingpin.actors.lasdfjk: 'module' object has no attribute 'lasdfjk'
2015-12-21 09:53:43,417 CRITICAL  Could not import lasdfjk: 'module' object has no attribute 'lasdfjk'
2015-12-21 09:53:43,417 CRITICAL  Dry run failed. Reason:
2015-12-21 09:53:43,417 CRITICAL  Unable to import "lasdfjk" as a valid Actor.
(.venv)Matts-MacBook:kingpin diranged$ echo $?
2
(.venv)Matts-MacBook:kingpin diranged$ 
```
=> Use kingpin.actors.utils.get_actor_class() when getting an actor from the CLI

kingpin/actors/aws/test/integration_cloudformation.py
Heads up @siminm, I'm just going to merge this. :)
=> Increase timeout on Deleting CloudFormation stack integration test.

docs/basicuse.rst
Sphinx 1.3.5 is much more sensitive to the LaTeX parser failing to
highlight due to formatting issues. Two bug fixes in our docs here to
help make the Sphinx happy again.
=> Fix documentation code-block bugs with latest Sphinx.

.gitignore, Makefile, docs/development.rst, kingpin/actors/aws/test/integration_base.py, kingpin/actors/aws/test/integration_cloudformation.py, kingpin/actors/aws/test/integration_elb.py, kingpin/actors/aws/test/integration_iam.py, kingpin/actors/aws/test/integration_sqs.py, kingpin/actors/misc.py, kingpin/actors/rightscale/test/integration_alerts.py, kingpin/actors/rightscale/test/integration_deployment.py, kingpin/actors/rightscale/test/integration_mci.py, kingpin/actors/rightscale/test/integration_server_array.py, kingpin/actors/support/test/integration_api.py, kingpin/actors/test/integration_hipchat.py, kingpin/actors/test/integration_librato.py, kingpin/actors/test/integration_misc.py, kingpin/actors/test/integration_pingdom.py, kingpin/actors/test/integration_rollbar.py, kingpin/actors/test/integration_slack.py, kingpin/actors/test/test_misc.py, setup.py
This commit finally closes issue #56 -- making each set of integration
tests optional by passing different attributes to the test suite runner.
=> Issue #56: Make each Integration test suite optional.

kingpin/actors/utils.py, kingpin/test/test_utils.py, kingpin/utils.py
We had a bunch of duplicated code causing multiple imports to happen
that didn't have to. Also, the __import__ module wasn't working as I had
hoped it would. Using importlib.import_module() is _much_ simpler, and
removing the bogus extra loop in the kingpin.utils.str_to_class() method
makes everything easier to understand.
@siminm
=> Bugfix our auto-actor-importer code.

kingpin/actors/aws/iam/entities.py
if we're ensuring that a group is absent, its OK if we get a 404 when
searching for the groups members.
Heads up @siminm, im going to merge this so our integration tests start working again.
=> Bugfix on IAM Group deletion.

kingpin/actors/rightscale/settings.py
It looks like RightScale has a new variation of the 422 return string
that we need to catch, and _not_ retry on.
After re-enabling our integration tests, I caught this failure a few times:
```
======================================================================
ERROR: integration_06d_execute_incorrect_inputs (integration_server_array.IntegrationServerArray)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/mnt/jenkins/workspace/ops-kingpin-continuous-build/venv/local/lib/python2.7/site-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/testing.py", line 132, in __call__
result = self.orig_method(*args, **kwargs)
File "/mnt/jenkins/workspace/ops-kingpin-continuous-build/venv/local/lib/python2.7/site-packages/tornado-4.3-py2.7 …
```
=> Fix the RightScale Retry Module -- Add another 422 string to NOT retry on

Makefile, docs/basicuse.rst, examples/simple.yaml, examples/test/sleep.yaml, kingpin/actors/aws/base.py, kingpin/actors/misc.py, kingpin/actors/test/test_misc.py, kingpin/bin/deploy.py, kingpin/exceptions.py, kingpin/schema.py, kingpin/test/test_schema.py, kingpin/test/test_utils.py, kingpin/utils.py, requirements.txt
Supporting both YAML and JSON is pretty easy. Most of this commit is
just renaming of methods so they are more generic (script instead of
json for example). Still missing a test though for the
convert_script_to_dict() method when the YAML parser is executed and it
fails.
@siminm, could you take a stab at the final missing unit test on junk YAML?
=> Support both YAML and JSON for the script file.

kingpin/actors/misc.py
First, make sure that on an http-downloaded script, we set the __repr__
of that in such a way that it can be parsed like a file name. Second,
restore the behavior of the convert_script_to_dict class so that we
catch LookupErrors and wrap them in an UnrecoverableActorFailure.
Review: @siminm
=> Fix the Macro Integration tests after the YAML switch.

docs/basicuse.rst, examples/misc.macro/inner.yaml, examples/misc.macro/outer.yaml, examples/misc.macro/outer_group.yaml, examples/misc.macro/outer_macro.yaml, examples/misc.macro/sleeper.yaml, kingpin/actors/base.py, kingpin/actors/group.py, kingpin/actors/misc.py, kingpin/actors/test/test_group.py, kingpin/actors/test/test_misc.py, kingpin/actors/utils.py, kingpin/bin/deploy.py
This patch implements a "token passing" system for the Group and Macro actors. These special actor types can pass in the "tokens" they were initialized with to each subsequent actor, allowing that actor to have the same access as the first one. This allows for a deeply nested Macro or Group actor to leverage a variable that was available at code launch time, but not necessarily passed to it.
Though this change is not backwards-incompatible -- its definitely a large change in the way we think about drawing up large and complex JSON/YAML scripts.
Closes #362.
=> Support deep nested token passing to macros and group actors

kingpin/actors/aws/base.py, kingpin/actors/base.py, kingpin/actors/group.py, kingpin/actors/misc.py, kingpin/bin/deploy.py, kingpin/version.py
The self._init_tokens are actually useful for all actors -- for example,
the AWS actors should be able to use them  when parsing cloudformation and
inline policies.
=> Make the 'init_tokens' available to all actors.

docs/conf.py, kingpin/actors/aws/s3.py, kingpin/actors/aws/test/integration_s3.py, kingpin/actors/aws/test/test_s3.py, requirements.txt
This adds full management (configuring, deleting and updating) of the S3
bucket lifecycle policies. As many policies can be defined as needed,
and they are all schema-checked as much as possible to ensure fast
detection of invalid policies.
=> Add Lifecycle Management support to the aws.s3.Bucket actor.

kingpin/actors/aws/s3.py, kingpin/actors/aws/test/test_s3.py, kingpin/actors/aws/test/test_sqs.py, kingpin/actors/utils.py
This fix has two parts -- one, I fix the bad calls where we were passing in
*args rather than *kwargs. Second, I moved the .format() call in the
@dry decorator so that its _always_ executed, and will fail any test case
where we execute that codepath incorrectly.
=> Bugfix -- Ensure the appropriate kwargs are used for the dry decorator.

docs/conf.py, examples/test/aws.cloudformation/cf.unittest.json, kingpin/actors/aws/base.py, kingpin/actors/aws/cloudformation.py, kingpin/actors/aws/test/integration_cloudformation.py, kingpin/actors/aws/test/test_cloudformation.py, kingpin/bin/deploy.py, requirements.txt, setup.py
This is step 1 ... use Boto3 rather than Boto. Boto3 will be required
for us to interact with CF Change Sets.
=> Convert aws.cloudformation.Create to use Boto3

.coveragerc
The newest version of coverage has show_missing set to false.
See: http://stackoverflow.com/questions/37733194/
=> Add .coveragerc file to show missing lines.

kingpin/actors/base.py, kingpin/actors/rightscale/alerts.py, kingpin/actors/rightscale/server_template.py, kingpin/actors/rightscale/test/integration_mci_and_st.py, kingpin/actors/rightscale/test/test_alerts.py, kingpin/actors/rightscale/test/test_server_template.py
No integration tests yet .. since this actor doesn't do any subject href discovery, its hard to test it as is. It will get integration tests when we create actors that subclass from this.
=> Create a new AlertSpecBase ensurable base actor for managing RightScale AlertSpecs

kingpin/actors/rightscale/alerts.py, kingpin/actors/rightscale/api.py, kingpin/actors/rightscale/server_array.py, kingpin/actors/rightscale/test/test_alerts.py, kingpin/actors/rightscale/test/test_api.py, kingpin/actors/rightscale/test/test_server_array.py
This also includes some cleanup to our RightScale error text handling to
make it more obvious when we have clean rightscale error text coming
back to us.
=> Bugfix -- handling a single alertspec on a template was broken

kingpin/actors/aws/base.py, kingpin/actors/aws/s3.py, kingpin/actors/aws/test/test_s3.py, kingpin/constants.py, requirements.txt
Boto3 supports the NoncurrentVersionExpiration/Transition settings that
allow us to set Lifecycle policies that truly delete data even in a
versioned bucket. Boto2 simply does not support this.
Migrating to Boto3 is enough work that I decided to also leverage the
new EnsurableBaseActor class to simplify much of the logic. Now there is
no more mocking out of a bucket object, passing around of this object,
etc. Instead we just issue get/set calls directly through the Boto3 API.
Note, WIP .. Tests are still in progress.
=> Convert the aws.s3.Bucket actor to use Boto3

kingpin/actors/aws/s3.py, kingpin/actors/aws/test/test_s3.py
The get_lifecycle/get_tags methods would fail if they were applied on a
resource that didn't yet exist. Oops.
=> Bugfixes around creation of new S3 buckets.

kingpin/actors/aws/base.py
Note that this means it won't care about str/unicode distinction anymore in diff.
I think we're okay with that, but I noted it in the docstring.
@diranged
=> Strip out unicode characters in diff_dicts.

kingpin/actors/aws/s3.py, kingpin/actors/aws/test/test_s3.py
We can't simply use the logic in the base class compare_xxx() method
because it takes into account order in lists, which don't matter with
tags. Instead we need a dedicated compare_tags() method that understands
this.
=> Compare S3 bucket tags with some intelligence.

kingpin/actors/aws/ecs.py, kingpin/actors/aws/test/integration_ecs.py, kingpin/actors/aws/test/test_ecs.py
=> ECS: Optionally reuse existing count when updating a service.

kingpin/actors/aws/iam/entities.py, kingpin/actors/aws/iam/test/test_entities.py, requirements.test.txt
If you have more than 100 iam entities, by default you have to paginate
the results. Build in pagination, but also set the max_items to 1000
(API limit) so that we can get all our results back in one API call.
This closes #446
=> Paginate the IAM get_all_entities() method call

kingpin/actors/aws/cloudformation.py, kingpin/actors/aws/test/test_cloudformation.py
This is the original feature with the fix for a bug where `Create` class can pass through `None` to `EnableTerminationProtection` because of how `None` is handled and then defaulted according to the configuration. With using the `UNCHANGED` string and logic on that, it is more explicit.
=> CF Actor - Add enable_termination_protection option (v2 fixed)

kingpin/actors/rightscale/api.py, kingpin/actors/rightscale/rightscript.py, kingpin/actors/rightscale/test/test_api.py, kingpin/actors/rightscale/test/test_rightscript.py, requirements.txt
The old code used a functional, but limited API endpoint
(http://reference.rightscale.com/api1.5/resources/ResourceRightScripts.html#update)
to PUT our Script 'Source' as a URL argument. This new code separates
the concept of updating script meta parameters, from its source. The
source is updated with a special dedicated url
(http://reference.rightscale.com/api1.5/resources/ResourceRightScripts.html#update_source)
and the body of the script data is pushed as part of the request
headers, rather than the URL arguments.
=> Bugfix on PUTing large RightScale Scripts

kingpin/actors/aws/ecs.py, kingpin/actors/aws/test/test_ecs.py
Instead of only passing along specfic parts, pass everything except for some specific parts that aren't allowed to change.
This'll allow us to more easily keep up with ECS feature changes.
=> Handle other parts of service definition indiscriminately.

kingpin/actors/aws/ecs.py, kingpin/actors/aws/test/test_ecs.py
They need default values for the immutability check, because the ECS api returns defaults if they're not set.
=> Add some more immutable fields now that we're passing them in update.

kingpin/actors/aws/ecs.py, kingpin/actors/aws/test/test_ecs.py
If they aren't supplied, amazon provides a default.
=> ECS: Stop setting defaults for immutable fields.

.travis.yml, kingpin/actors/aws/api_call_queue.py, kingpin/actors/aws/base.py, kingpin/actors/aws/cloudformation.py, kingpin/actors/aws/ecs.py, kingpin/actors/aws/elb.py, kingpin/actors/aws/elbv2.py, kingpin/actors/aws/iam/certs.py, kingpin/actors/aws/iam/entities.py, kingpin/actors/aws/s3.py, kingpin/actors/aws/sqs.py, kingpin/actors/aws/test/test_api_call_queue.py, kingpin/actors/aws/test/test_base.py, kingpin/actors/aws/test/test_cloudformation.py, kingpin/actors/aws/test/test_elbv2.py, kingpin/actors/aws/test/test_s3.py, kingpin/version.py
This will serialize all the requests to the CloudFormation describe_stacks API to better protect against rate limits.
This is a pretty complicated implementation, and I don't like how it integrates with testing at the moment.
Each test creates a new ioloop, breaking the existing ApiCallQueues, as the process_queue callback will not be re-entered. Haven't figured out a way around this yet other than clearly the ApiCallQueues between tests.
=> Integrate an API Call Queue for cf.describe_stacks.

docs/installation.rst, requirements.txt, setup.py
Thanks to https://github.com/pypa/pip/issues/4187#issuecomment-452862842, we can finally install
Kingpin easily with a simple `pip install` command.
=> Use PEP 508 URL formatting for easier Pip install

kingpin/actors/aws/cloudformation.py, kingpin/actors/aws/test/test_cloudformation.py, kingpin/version.py
When using SSM parameters the resolved values are returned for the stack. They can't be compared as the local params aren't resolved (obviously).
=> Filter out ResolvedValue from the params

Makefile
We already use PEP-0508, so we're good to go without this option.
https://www.python.org/dev/peps/pep-0508/#examples
https://mail.python.org/pipermail/distutils-sig/2013-October/022937.html
=> make kingpin.zip - remove process dep links option (deprecated)

kingpin/actors/aws/cloudformation.py, kingpin/actors/aws/test/test_cloudformation.py
Display status reasons to clarify errors and improve debugging during kingpin runs.
`describe_stacks` returns a `StackStatusReason`: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html#using-cfn-describing-stacks-describe-stacks
`describe-change-set` returns a `StatusReason`: https://docs.aws.amazon.com/cli/latest/reference/cloudformation/describe-change-set.html#examples
=> Log status reason on stack and change set failures

requirements.txt
zipp>=2.0.0 drops support for python 2.
=> Downgrade zipp

kingpin/actors/aws/cloudformation.py, kingpin/actors/aws/test/test_cloudformation.py, requirements.txt
There are 3 CFN functions/states here that do slightly different things and it helps to know which function/state you are in when looking at kingpin errors.
1. Failed to create a stack (_wait_until_state)
2. Failed to create a change set (_wait_until_change_set_ready where status='Status')
3. Failed to execute a change set (ie. update a stack) (_wait_until_change_set_ready where status='ExecutionStatus')
Thanks to @smmorneau for originally finding where to edit these.
#481 
#482
=> Better Exception Messages in AWS CFN Actors

requirements.txt
Changing line 33 to `python-rightscale @ https://github.com/diranged/python-rightscale-1/tarball/nextdoor#egg=python-rightscale` will save the egg using the same names as the lib's name, which will allow Snyk to identify and link the library with its sources.
=> Fix Snyk Integration

kingpin/actors/aws/s3.py, kingpin/actors/aws/test/test_s3.py
AWS added a new API to change some of the functionality slightly. You can now use Filter>Prefix instead of just Prefix to add multiple lifecycle policy rules onto the same prefixes. Not quite sure how it determines which policy wins but I will leave that as an exercise for the reader.
=> S3 Lifecycle Policy: Add Filter Option

kingpin/actors/aws/s3.py, kingpin/actors/aws/test/test_s3.py
Fixes:
```
19:58:23   CRITICAL  [S3 Bucket] Invalid Lifecycle Configuration: Parameter validation failed:
Unknown parameter in LifecycleConfiguration.Rules[0]: "Transition", must be one of: Expiration, ID, Prefix, Filter, Status, Transitions, NoncurrentVersionTransitions, NoncurrentVersionExpiration, AbortIncompleteMultipartUpload
```
Here are the API Changes when we switched to using `put_bucket_lifecycle_configuration `:
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.put_bucket_lifecycle
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.put_bucket_lifecycle_configuration
=> S3 LCP: Fix Transitions API Key

kingpin/actors/base.py, kingpin/actors/group.py, kingpin/test/test_utils.py, kingpin/utils.py
There's an interesting usage issue when it comes to `populate_with_tokens`. This function is actually called multiple times over subsets of an input.
Consider:
```
---
- actor: aws.cloudformation.Stack
options:
name: FOBAR
region: 'us-east-1'
template: mystack.yaml
parameters:
Param1: foo
Param2: \{bar\}
```
Because the above is actually wrapped by a `kingpin.actors.group.Sync` actor `populate_with_tokens` is called over the entire input.
The input is:
```
{
"acts": [{
"actor": "aws.cloudformation.Stack",
"options": {
"name": "FOBAR",
"region": "us-east-1",
"template": "mystack.yaml",
"parameters": {
"Param1": "foo",
"Param2": "\\{bar\\}"
}
}
}]
}
```
The output is:
```
{
"acts": [{
"actor": "aws.cloudformation.Stack",
"options": {
"name": "FOBAR",
"region": "us-east-1",
"template": …
```
=> remove escaping in non strict mode and fix escaped_tokens

kingpin/actors/aws/cloudformation.py, kingpin/actors/aws/test/test_cloudformation.py
This implementation requires the user to explicitly provide a S3 bucket and key to their template.
=> Add support for CFN templates in S3

examples/test/aws.cloudformation/cf.integration.yaml, kingpin/actors/aws/cloudformation.py, kingpin/actors/aws/test/test_cloudformation.py, kingpin/test/test_utils.py, kingpin/utils.py, requirements.txt
While trying to add Datadog's [MetricStream CFN stack](https://datadog-cloudformation-stream-template.s3.amazonaws.com/aws/streams_main.yaml), I hit two issues with KingPin.
1. It uses the shorthand functions `!GetAtt` and `!Sub` a lot. 
2. The `Version` in Policy documents was unquoted, so PyYaml natively parsed it as a date which then failed to JSON dump. 
This is currently failing tests due to coveragee, but I do not see many examples of YAML based CFN stacks that would be easy to build upon. 
@diranged @stlava Does this seem like a reasonable idea to you two?
=> Add support for !GetAtt, !Sub and datetime by using Amazon's cfn-flip to parse YAML

kingpin/actors/aws/iam/entities.py, kingpin/actors/aws/iam/test/test_entities.py, kingpin/version.py
It turns out that in Boto3 you _must_ supply the
AssumeRolePolicyDocument - AWS will not create the default document for
you. For that reason, we change our default behavior here to set the
`assume_role_policy_document` setting to the default EC2 policy
document.
=> [iam.role] Fix IAM Role creation with Boto3

docs/conf.py, kingpin/actors/aws/iam/entities.py, kingpin/version.py
I was passing in a string rather than a string-pointer to a file, and
that's not what the input was expecting. This is a simpler fix.
=> [actors.aws.entities] Bugfix the IAM Role Creation actor

.circleci/config.yml
Example deprecation warning we are seeing with the old CircleCI image:
> You’re using a deprecated Docker convenience image. Upgrade to a next-gen Docker convenience image.
=> [ci/cd] Update CircleCI Image

kingpin/actors/aws/base.py, kingpin/actors/aws/settings.py
We simply forward the `AWS_*` env vars into the config if they are set. Otherwise we will just use some sane default parameters which we have found work well based on our understanding of the commented documentation and our experience in running kingpin at scale.
=> [AWSBaseActor] Respect boto3/AWS retry configurability

kingpin/actors/aws/cloudformation.py, kingpin/actors/aws/settings.py, kingpin/actors/aws/test/test_cloudformation.py, kingpin/version.py
This error appears sometimes when editing a cfn template:
> 00:39:22 CRITICAL [DRY: S3-LOGGING-BUCKET (us-east-2)] Unexpected Change Set state (Status) received (FAILED): No updates are to be performed.
This is a bit of an oddity between `kingpin` and CFN.
`kingpin` is pushing an update to CFN because the template has changed, but CFN is denying that there are any changes because physical resources in CFN template have not actually changes. This is likely because the PR is only making changes to conditional resources in the CFN template yet there are CFN stacks using this template that do not deploy that conditional resource - therefore leading to CFN believing there was "no update".
~~To resolve this, they need to bump the metadata in the CFN template on a non-conditional resource.~~
^ …
=> feat(cfn): Append hash to outputs

.github/nextdoor.yml, .github/release-drafter.yml, .github/workflows/prlint.yml, .github/workflows/release_drafter.yml, .github/workflows/stale.yml, renovate.json
- Add renovate
- Add conventional commits (PR linter)
- Add stale branch finder
- Add release drafter
- Add dev automations (ND internal)
=> feat(ci): Add a bunch of boilerplate automation goodies

.vscode/settings.json, kingpin/actors/aws/test/test_iam.py, kingpin/actors/base.py, kingpin/version.py
- Disabled broken IAM test (currently blocking other critical fix items)
- Added vscode testing config
- Removed unused exception handling
=> fix(iam): Disable broken IAM test

kingpin/actors/aws/test/test_iam.py, kingpin/version.py
boto3 Stubber expects calls to come in order. However, our code (or the underlying libraries) can do calls in a random order. This PR helps eliviate the in order expectations.
=> fix(ci): Fix flaky tests related to stubber out of order expectations
