Nextdoor/kingpin

kingpin/actors/rightscale/api.py
kingpin/actors/rightscale/test/test_api.py

Add logger test in wait_for_task

---

kingpin/actors/rightscale/api.py
kingpin/actors/rightscale/server_array.py
kingpin/actors/rightscale/test/test_api.py
kingpin/actors/rightscale/test/test_server_array.py
kingpin/bin/deploy.py

Show instance audit logs when Execute task fails.

---

kingpin/actors/rightscale/api.py
kingpin/actors/rightscale/test/test_api.py

Don't fetch audit logs if the instance is missing

---

requirements.txt
setup.py

Pull request is pending with author:
https://github.com/brantai/python-rightscale/pull/11
(Issue #189)

Use the patched python-rightscale library with auto-token-refreshment.

---

kingpin/actors/support/api.py
kingpin/actors/support/test/test_api.py

Fix API default exception raising.

---

kingpin/actors/aws/base.py
kingpin/actors/aws/test/integration_base.py

Catch InvalidCredentials in AWS Base class.

---

README.md
docs/actors/aws.elb.RegisterInstance.md
kingpin/actors/aws/base.py
kingpin/actors/aws/elb.py
kingpin/actors/aws/test/integration_base.py
kingpin/actors/aws/test/test_base.py
kingpin/actors/aws/test/test_elb.py

Add zones to ELB automatically.

---

docs/actors/aws.cloudformation.Create.md
docs/actors/aws.cloudformation.Delete.md
docs/actors/aws.elb.DeregisterInstance.md
docs/actors/aws.elb.RegisterInstance.md
docs/actors/aws.elb.SetCert.md
docs/actors/aws.elb.WaitUntilHealthy.md
docs/actors/aws.sqs.Create.md
docs/actors/aws.sqs.Delete.md
docs/actors/aws.sqs.WaitUntilEmpty.md
kingpin/actors/aws/base.py
kingpin/actors/aws/cloudformation.py
kingpin/actors/aws/elb.py
kingpin/actors/aws/sqs.py
kingpin/actors/aws/test/test_base.py

Convert a Zone into a Region on the fly.

---

.travis.yml
requirements.txt
setup.py

Fix pip install by updating python-rightscale dependency.

---

kingpin/actors/rightscale/api.py
kingpin/actors/rightscale/server_array.py
kingpin/actors/rightscale/test/integration_server_array.py
kingpin/actors/rightscale/test/test_api.py
kingpin/actors/rightscale/test/test_server_array.py

Support rightscale launch count option

---

CHANGELOG.md
README.md
WHATSNEW.md
kingpin/actors/aws/test/integration_elb.py
kingpin/actors/aws/test/test_cloudformation.py
kingpin/actors/base.py
kingpin/actors/exceptions.py
kingpin/actors/rightscale/test/test_server_array.py
kingpin/actors/test/test_base.py
kingpin/schema.py
requirements.txt

Add Execution timeout setting to BaseActor

---

WHATSNEW.md
docs/actors/rightscale.server_array.Destroy.md
docs/actors/rightscale.server_array.Terminate.md
kingpin/actors/rightscale/server_array.py
kingpin/actors/rightscale/test/test_server_array.py

Add 'strict' parameter to the rightscale.server_array.Destroy/Terminate actors

---

README.md
docs/actors/pingdom.Pause.md
docs/actors/pingdom.Unpause.md
kingpin/actors/pingdom.py
kingpin/actors/support/api.py
kingpin/actors/test/helper.py
kingpin/actors/test/integration_pingdom.py
kingpin/actors/test/test_pingdom.py
kingpin/utils.py

Add pingdom.Pause/Unpause actors.

---

kingpin/actors/support/api.py
kingpin/actors/support/test/integration_api.py
kingpin/actors/support/test/test_api.py
kingpin/utils.py

General improvements to the testing, and logging of this package. Hides passwords/tokens in logging and reduces unnecessary debug logging.

Authentication testing/logging improvements to actors.support.api Package

---

kingpin/actors/aws/elb.py
kingpin/actors/aws/settings.py
kingpin/actors/aws/test/test_settings.py

Do not leverage PleaseRetryException to handle Throttling

---

kingpin/actors/base.py
kingpin/actors/group.py
kingpin/actors/misc.py

Fix the default_timeout=0 class setting on Group/Macro actors.

---

README.md
kingpin/bin/deploy.py

Allow skipping of the automated dry run.

---

kingpin/actors/aws/elb.py

We were making an API call here with no retry decorator at all. Oops!
Now we're using the self.thread() method to handle the API call and deal
with all the retry logic.

Use self.thread() in elb.WaitUntilHealthy._is_healthy() method.

---

docs/actors/group.Sync.md
kingpin/actors/group.py
kingpin/actors/test/test_group.py

Show all errors in Dry run before failing.

---

docs/conf.py

Nextdoorify Sphinx Documentation

---

docs/conf.py

Reverts #274 - Not sexy enough. Waiting for https://github.com/snide/sphinx_rtd_theme to enable `html_theme_options`

Revert "Nextdoorify Sphinx Documentation"

---

kingpin/actors/group.py
kingpin/actors/test/test_group.py

Allow Async actor to limit concurrency

---

README.rst

Fix pypi link in README.rst

---

docs/kingpin.actors.rightscale.rst
kingpin/actors/rightscale/deployment.py
kingpin/actors/rightscale/test/integration_deployment.py
kingpin/actors/rightscale/test/test_deployment.py

```
$ nosetests kingpin/actors/rightscale/test/integration_deployment.py --include=integration
....
----------------------------------------------------------------------
Ran 4 tests in 5.862s
OK
```

Create rightscale deployment Destroy actor

---

.gitignore
.travis.yml
docs/kingpin.actors.packagecloud.rst
docs/modules.rst
kingpin/actors/base.py
kingpin/actors/packagecloud.py
kingpin/actors/test/test_packagecloud.py
requirements.txt

@siminm @diranged  Review please.  No tests so far, so just let me know if this looks good so far and if so, I'll add tests.

Packagecloud Actor

---

kingpin/actors/aws/test/integration_cloudformation.py
kingpin/actors/rightscale/test/integration_alerts.py
requirements.txt

Fix alert tests

---

requirements.txt
setup.py

@siminm, can you review this and the underlying python-rightscale change that i made? if you think its decent enough, we can at least merge this into our code base..

Depend on the newest RightScale library patch.

---

docs/kingpin.actors.rightscale.rst
kingpin/actors/rightscale/api.py
kingpin/actors/rightscale/base.py
kingpin/actors/rightscale/mci.py
kingpin/actors/rightscale/test/integration_mci.py
kingpin/actors/rightscale/test/test_api.py
kingpin/actors/rightscale/test/test_mci.py

Initial support for creating and destroying RightScale MCIs.

---

docs/index.rst

Fix doc typo

---

kingpin/actors/base.py
kingpin/actors/test/test_base.py

Allow contexts in conditions

---

kingpin/actors/rightscale/base.py
kingpin/actors/rightscale/test/test_base.py
kingpin/actors/rightscale/test/test_mci.py

Don't sort rightscale params.

---

docs/basicuse.rst
kingpin/actors/misc.py
kingpin/bin/deploy.py
kingpin/schema.py

Allow actor input from command line rather than json file.

---

kingpin/actors/rightscale/server_array.py
kingpin/actors/rightscale/test/test_server_array.py

Allow server_array.Launch to not enable and not launch.

---

kingpin/actors/slack.py
kingpin/actors/test/test_slack.py

Allow a list of channels for slack.Message

---

kingpin/actors/test/test_group.py

Instead of checking sleep-time correctness I check order of execution
correctness.
Also this saves us 0.3s during unit tests :)
@diranged

Rewrite async test to make pypy happy

---

docs/conf.py
kingpin/actors/misc.py
requirements.test.txt

cc: @bemsha @niallo @diranged @nrvale0

Add data-json to GenericHTTP actor

---

docs/basicuse.rst
kingpin/bin/deploy.py

review: @Nextdoor/engineering-opensource-collaborators

Add --build-only flag to kingpin

---

requirements.test.txt

Needed for sphinx build.
Please review @diranged @siminm

add functools32 as a test dep

---

kingpin/actors/aws/iam/__init__.py
kingpin/actors/aws/iam/entities.py
kingpin/actors/aws/iam/test/integration_entities.py
kingpin/actors/aws/iam/test/test_entities.py

This initial work just allows us to create a role and manage its inline
policies. I still have work to do to make sure that the role is usable
by other instance profiles.
Reviewer: @siminm

New Actor - aws.iam.Role

---

docs/development.rst
kingpin/actors/aws/iam/entities.py
kingpin/actors/aws/iam/test/test_entities.py

We've decided to refactor this code so that if a user simply does not
supply `inline_policies` or `groups` to the actors, then they
automatically do not manage these attributes. If they DO supply either
of these, then we automatically own the resource attributes entirely.

Issue 342 -- Remove explicit 'purge' options from AWS IAM Actors

---

docs/basicuse.rst
docs/development.rst
kingpin/actors/aws/cloudformation.py
kingpin/actors/aws/elb.py
kingpin/actors/base.py
kingpin/actors/hipchat.py
kingpin/actors/librato.py
kingpin/actors/misc.py
kingpin/actors/packagecloud.py
kingpin/actors/pingdom.py
kingpin/actors/rollbar.py
kingpin/actors/slack.py
kingpin/actors/test/test_base.py
kingpin/bin/deploy.py
kingpin/schema.py

Make the `desc` parameter optional

---

kingpin/actors/rightscale/server_array.py
kingpin/actors/rightscale/test/test_server_array.py

Search for the "default" RightScale MCI HREF even in the DRY run.

---

examples/aws.iam.role/lambda.json
kingpin/actors/aws/iam/entities.py
kingpin/actors/aws/iam/test/test_entities.py

Add support for managing IAM Trust Relationships

---

docs/development.rst
docs/kingpin.actors.aws.rst
docs/modules.rst
kingpin/actors/aws/s3.py
kingpin/actors/aws/test/integration_s3.py
kingpin/actors/aws/test/test_s3.py
kingpin/actors/base.py
kingpin/constants.py

Add Bucket Logging Configuration support to the aws.s3.Bucket actor.

---

kingpin/actors/aws/s3.py
kingpin/actors/aws/test/integration_s3.py
kingpin/actors/aws/test/test_s3.py

Add bucket versioning management to the aws.s3.Bucket actor

---

.travis.yml

Review: @niallo @swaggy 
Heads up: @diranged

Remove pypy from Travis tests.

---

docs/kingpin.actors.rightscale.rst
kingpin/actors/rightscale/__init__.py
kingpin/actors/rightscale/api.py
kingpin/actors/rightscale/base.py
kingpin/actors/rightscale/mci.py
kingpin/actors/rightscale/server_array.py
kingpin/actors/rightscale/test/integration_mci.py
kingpin/actors/rightscale/test/test_api.py
kingpin/actors/rightscale/test/test_base.py
kingpin/actors/rightscale/test/test_mci.py
kingpin/actors/rightscale/test/test_server_array.py

cc @diranged 
Just opening this to keep track of changes. Please do not review this atrocity yet!

Create rightscale.MCI actor for managing MCIs

---

kingpin/actors/aws/base.py
kingpin/actors/aws/ecs.py
kingpin/actors/aws/test/test_ecs.py
requirements.txt

Add ECS actor

---

kingpin/actors/aws/ecs.py
kingpin/actors/aws/test/test_ecs.py

Improve logging and error handling for ecs actor.

---

kingpin/actors/misc.py
kingpin/actors/test/test_misc.py

Add misc.Note actor

---

kingpin/actors/aws/ecs.py
kingpin/actors/aws/test/test_ecs.py

Add more ECS run task logs.

---

docs/kingpin.actors.aws.rst
kingpin/actors/aws/ecs.py
kingpin/actors/aws/test/test_ecs.py

Add ECS service actor. Still working on unit tests, then integration tests.
@mikhail @diranged

Add ecs service actor.

---

kingpin/actors/aws/s3.py
kingpin/actors/aws/test/test_s3.py

Bugfix -- we couldn't create S3 buckets in anything other than the default region.

---

kingpin/test/test_utils.py
kingpin/utils.py

Add default values to tokenized strings

---

kingpin/actors/aws/ecs.py

ECS: Add retry logic to methods that had API race conditions.

---

kingpin/actors/aws/base.py
kingpin/actors/aws/ecs.py
kingpin/actors/aws/test/test_ecs.py

Add state to ECS services. Allow deleting a service.

---

kingpin/actors/aws/ecs.py
kingpin/actors/aws/settings.py
kingpin/actors/aws/test/test_ecs.py

Fix retries in ECS.

---

kingpin/actors/aws/ecs.py

Make count accept a string. Boto will convert it.

---

kingpin/actors/aws/ecs.py
kingpin/actors/aws/test/test_ecs.py

Convert count if not int.

---

kingpin/actors/aws/ecs.py
kingpin/actors/aws/test/test_ecs.py

This update improves logging, documentation, and script readability of the ECS service actor.
It also cleans up old task definitions.
Changes:
* Refactor from using _ensure_service.
Previously, deletion was logging many lines with misleading text such as 'Deployed successfully'.
Additionally, ensure_service's documentation talks about only 'updating' a service. This goes back to giving it that single responsibility.
* Clean up documentation to include the 'absent' desired state, plus other misc. documentation improvements.
* Split stop service from delete service. This allows us to add a way of only stopping and not deleting in the future, if we need.
* Add correct logging for deletion.
* Rename wait_for_deployment and is_service_deployed to wait_for_service_update and is_service_updated. …

Improve ECS service deletion.

---

kingpin/actors/aws/ecs.py
kingpin/actors/aws/test/test_ecs.py

ECS: Use pagination for list task definitions.

---

kingpin/actors/aws/ecs.py
kingpin/actors/aws/test/test_ecs.py

Handle case where service is in 'DRAINING' state for deletion.

---

kingpin/actors/rightscale/server_array.py
kingpin/actors/rightscale/test/test_server_array.py

Launch max_count machines if no `count` value specified.

---

kingpin/actors/rightscale/base.py

Heads up @diranged . Merging this

Add max_count to rightscale dryrun mock

---

kingpin/actors/aws/ecs.py
kingpin/actors/aws/test/test_ecs.py

Handle ECS race condition for non-existent service

---

kingpin/actors/aws/ecs.py
kingpin/actors/aws/test/test_ecs.py

Fix ecs service creation

---

kingpin/actors/aws/base.py
kingpin/actors/aws/cloudformation.py
kingpin/actors/aws/ecs.py
kingpin/actors/aws/iam/entities.py
kingpin/actors/aws/s3.py
kingpin/actors/aws/settings.py
kingpin/actors/aws/test/integration_ecs.py
kingpin/actors/aws/test/test_base.py
kingpin/actors/aws/test/test_ecs.py
requirements.txt

@diranged @niallo @mikhail @ashanbrown 
Functionally finished, integration tests WIP.

Make ECS service stateful.

---

kingpin/actors/aws/ecs.py

ECS: Fix a race condition in stop service

---

Makefile
docs/basicuse.rst
docs/kingpin.actors.spotinst.rst
docs/modules.rst
examples/test/spotinst.elastigroup/unittest.b64.json
examples/test/spotinst.elastigroup/unittest.json
kingpin/actors/aws/base.py
kingpin/actors/aws/cloudformation.py
kingpin/actors/aws/iam/entities.py
kingpin/actors/aws/s3.py
kingpin/actors/aws/test/test_base.py
kingpin/actors/spotinst.py
kingpin/actors/test/integration_spotinst.py
kingpin/actors/test/test_spotinst.py
kingpin/constants.py
kingpin/test/test_utils.py
kingpin/utils.py
requirements.txt

@mikhail, this is ready for its first review I think. Its dependent on https://github.com/Nextdoor/tornado_rest_client/pull/4. The initial functionality is limited to Create/Delete/Update existing group. There is no waiting for instances to boot/terminate, or rolling releases. That will come though in future changes.
*ToDo*
Thoughts so far?

New Actor: spottinst.ElastiGroup

---

kingpin/actors/aws/ecs.py

@diranged @mikhail @niallo 
About once every two weeks we run into a case where the actor hangs on updating primary deployment. I've made the same API calls at those times and looked in the ECS console - everything looks fine. And yet it's stuck.
I don't like having to do this, but I need some more information. This'll print out more local variables and the exception message, which'll help me get to the bottom of this bug.

Add more logging to Kingpin to help debug rare ECS race condition.

---

examples/test/aws.cloudformation/cf.integration.json
kingpin/actors/aws/cloudformation.py
kingpin/actors/aws/test/integration_cloudformation.py
kingpin/actors/aws/test/test_cloudformation.py

@diranged please review when you get a chance.

Support default parameters in Cloudformation templates.

---

kingpin/actors/aws/cloudformation.py
kingpin/actors/aws/test/test_cloudformation.py

@diranged Still need to finish updating docs and tests, but I wanted to get your eyes on the implementation here.

CF Actor - Add enable_termination_protection option

---

.travis.yml
kingpin/version.py

Travis added a "feature" that broke our releases.

Add skip_cleanup: true

---

kingpin/actors/aws/cloudformation.py
kingpin/actors/aws/test/test_cloudformation.py
kingpin/version.py

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.get_template

Compare the Original CloudFormation Template Body

---

kingpin/actors/aws/cloudformation.py

Fixed some example errors (transposed) in aws.cloudformation.Create and aws.cloudformation.Stack.

Update cloudformation.py documentation

---

kingpin/actors/aws/cloudformation.py
kingpin/actors/aws/test/test_cloudformation.py

Revert "Log status reason on stack and change set failures"

---

kingpin/actors/aws/s3.py
kingpin/actors/aws/test/test_s3.py

Revert "S3 LCP: Fix Transitions API Key"

---

kingpin/actors/aws/s3.py
kingpin/actors/aws/test/test_s3.py

Revert "S3 Lifecycle Policy: Add Filter Option"

---

kingpin/actors/aws/s3.py
kingpin/actors/aws/test/test_s3.py

This is https://github.com/Nextdoor/kingpin/pull/496 and https://github.com/Nextdoor/kingpin/pull/497 combined with some enhancements to keep backwards compatibility in the kingpin API.

S3 Lifecycle Policy Config: Upgrade S3 API Call

---

kingpin/version.py

Routine increment of version post release.

Bump to version 1.0.1
